### ISSUE TITLE
powershell.el required

### ISSUE THREAD

**Issue by sdaaish** [kiennq/lsp-powershell#10]
To me it looks like `powershell.el` is needed to get into **powershell-mode**. So maybe this should be a requirement in `lsp-powershell`.

Or an instruction to show how to achieve this without that (a link possibly).
At least this is what I had to do to make this work.

This was my setup: https://github.com/sdaaish/emacs-demo/blob/master/lsp/init.el

**Comment by kiennq** [comment]
`lsp-powershell` should work even without `powershell.el`.
However in my example, its loading is hooked into `powershell-mode`, which is provided by `powershell.el` so the example will need `powershell.el` to work.
I will change the example to reflect that.

**Comment by kiennq** [comment]
See 99ac856
