### ISSUE TITLE
Installation with quelpa

### ISSUE THREAD

**Issue by ASCIIFry** [kiennq/lsp-powershell#9]
I tried installing lsp-pwsh with quelpa as described in the readme but it fails. Running it again with toggle-debug-on-error enabled shows it tries to clone from https://github.com/nil.git .

However changing 
`(quelpa '(lsp-pwsh :fetcher github :url "kiennq/lsp-powershell"))`

to
`(quelpa '(lsp-pwsh :fetcher github :repo "kiennq/lsp-powershell"))`

seems to fix this. Maybe you want to adjust your readme.
Thanks

**Comment by kiennq** [comment]
Thanks you.
I would hope for you to provide PR in the future too :)
